"use client";
import { useEffect, useState } from "react";
import { Award, Download } from "lucide-react";
export default function P() {
  const [certs,setCerts]=useState<any[]>([]);const [l,setL]=useState(true);
  useEffect(()=>{fetch("/api/certificates").then(r=>r.json()).then(d=>{setCerts(d.certificates||[]);setL(false)});},[]);
  const download=async(cert:any)=>{const{jsPDF}=await import("jspdf");const doc=new jsPDF({orientation:"landscape",unit:"mm",format:"a4"});doc.setDrawColor(200,169,81);doc.setLineWidth(2);doc.rect(8,8,281,194);doc.setLineWidth(0.5);doc.rect(12,12,273,186);doc.setFont("helvetica","bold");doc.setFontSize(32);doc.setTextColor(30,58,95);doc.text("Za-Campus University",148,40,{align:"center"});doc.setFontSize(16);doc.setTextColor(100,100,100);doc.text("Certificate of Completion",148,60,{align:"center"});doc.setFontSize(28);doc.setTextColor(30,58,95);doc.text(cert.student.firstName+" "+cert.student.lastName,148,85,{align:"center"});doc.setFontSize(14);doc.setTextColor(80,80,80);doc.text("has successfully completed the course",148,100,{align:"center"});doc.setFontSize(22);doc.setTextColor(200,169,81);doc.text(cert.class.name,148,120,{align:"center"});doc.setFontSize(12);doc.setTextColor(100,100,100);doc.text("Score: "+cert.score+"/"+cert.maxScore+"  |  Date: "+new Date(cert.issueDate).toLocaleDateString(),148,145,{align:"center"});doc.text("Certificate ID: "+cert.certificateNumber,148,155,{align:"center"});doc.setFontSize(10);doc.setTextColor(150,150,150);doc.text("Verified by Za-Campus University",148,180,{align:"center"});doc.save("Certificate_"+cert.certificateNumber+".pdf");};
  if(l) return <div className="flex justify-center py-16"><div className="w-8 h-8 border-2 border-primary border-t-transparent rounded-full animate-spin"/></div>;
  return (<div className="space-y-6 animate-fade-in"><div><h1 className="text-2xl font-bold text-gray-900">My Certificates</h1><p className="text-gray-500 mt-1">Download your earned certificates</p></div>{certs.length===0?<div className="card-premium p-12 text-center"><Award className="w-16 h-16 text-gray-300 mx-auto mb-4"/><h3 className="text-lg font-semibold text-gray-700 mb-1">No Certificates Yet</h3><p className="text-gray-500 text-sm">Complete a final exam with 12/20 to earn your certificate.</p></div>:<div className="grid md:grid-cols-2 gap-6">{certs.map(c=>(<div key={c.id} className="card-premium p-6 border-amber-100"><div className="flex items-start gap-4"><div className="w-12 h-12 rounded-xl bg-amber-100 flex items-center justify-center"><Award className="w-6 h-6 text-amber-600"/></div><div className="flex-1"><span className="text-xs font-medium text-amber-600 bg-amber-50 px-2 py-0.5 rounded-full">{c.class?.code}</span><h3 className="font-semibold mt-1">{c.class?.name}</h3><p className="text-sm text-gray-500 mt-1">Score: <span className="font-medium">{c.score}/20</span> · {new Date(c.issueDate).toLocaleDateString()}</p></div></div><button onClick={()=>download(c)} className="mt-4 w-full flex items-center justify-center gap-2 bg-amber-50 hover:bg-amber-100 text-amber-700 font-medium text-sm py-2.5 rounded-xl"><Download className="w-4 h-4"/>Download PDF</button></div>))}</div>}</div>);
}
