"use client";
import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { ArrowLeft, CheckCircle, XCircle, Trophy } from "lucide-react";
export default function P() {
  const params=useParams();const router=useRouter();const [quiz,setQuiz]=useState<any>(null);const [answers,setAnswers]=useState<Record<string,string>>({});const [submitted,setSubmitted]=useState(false);const [result,setResult]=useState<any>(null);const [passed,setPassed]=useState(false);const [l,setL]=useState(true);const [submitting,setSubmitting]=useState(false);
  useEffect(()=>{fetch("/api/final-quizzes/"+params.id).then(r=>r.json()).then(d=>{setQuiz(d.finalQuiz);setL(false)});},[params.id]);
  const submit=async()=>{if(submitting)return;setSubmitting(true);const res=await fetch("/api/final-quizzes/"+params.id+"/submit",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({answers})});const data=await res.json();setResult(data.attempt);setPassed(data.passed);setSubmitted(true);setSubmitting(false);};
  if(l) return <div className="flex justify-center py-16"><div className="w-8 h-8 border-2 border-primary border-t-transparent rounded-full animate-spin"/></div>;
  if(!quiz) return <div className="py-16 text-center text-gray-500">Not found</div>;
  if(submitted&&result) return (<div className="max-w-2xl mx-auto space-y-6 animate-scale-in"><div className={`card-premium p-8 text-center ${passed?"border-emerald-200":"border-red-200"}`}><div className={`w-16 h-16 rounded-full mx-auto mb-4 flex items-center justify-center ${passed?"bg-emerald-100":"bg-red-100"}`}>{passed?<CheckCircle className="w-8 h-8 text-emerald-600"/>:<XCircle className="w-8 h-8 text-red-600"/>}</div><h1 className="text-2xl font-bold mb-2">{passed?"Congratulations! You Passed!":"Not This Time"}</h1><p className="text-gray-500 mb-6">{passed?`You scored ${result.score}/20! Your certificate is now available.`:`Scored ${result.score}/20. Need 12/20 to pass.`}</p><div className="flex justify-center gap-8 mb-6"><div><div className="text-3xl font-bold">{result.score}/20</div><div className="text-xs text-gray-500">Score</div></div><div className="w-px h-12 bg-gray-200"/><div><div className={`text-3xl font-bold ${passed?"text-emerald-600":"text-red-600"}`}>{result.percentage}%</div><div className="text-xs text-gray-500">Pct</div></div></div><div className="flex gap-3 justify-center"><button onClick={()=>router.push("/student/classes/"+quiz.class.id)} className="bg-primary text-white px-6 py-2.5 rounded-xl text-sm">Back to Class</button>{passed&&<button onClick={()=>router.push("/student/certificates")} className="bg-amber-600 text-white px-6 py-2.5 rounded-xl text-sm"><Trophy className="w-4 h-4 inline mr-1"/>View Certificate</button>}</div></div></div>);
  return (<div className="max-w-2xl mx-auto space-y-6 animate-fade-in"><button onClick={()=>router.back()} className="flex items-center gap-2 text-sm text-gray-500 hover:text-gray-900"><ArrowLeft className="w-4 h-4"/>Back</button><div className="card-premium p-6 border-amber-200 bg-amber-50/10"><div className="flex items-center gap-3 mb-3"><Trophy className="w-6 h-6 text-amber-600"/><span className="text-xs font-medium text-amber-700 bg-amber-100 px-2 py-0.5 rounded-full">Final Exam</span></div><h1 className="text-xl font-bold">{quiz.title}</h1><p className="text-sm text-gray-500 mt-1">{quiz.description}</p><p className="text-sm text-amber-700 mt-2 font-medium">Score 12/20 or higher to pass and earn your certificate!</p></div><div className="space-y-4">{quiz.questions.map((q:any,i:number)=>{const opts:string[]=JSON.parse(q.options);return (<div key={q.id} className="card-premium p-5"><p className="text-sm font-semibold mb-3">{i+1}. {q.questionText}</p><div className="space-y-2">{opts.map((opt:string)=>(<label key={opt} className={`flex items-center gap-3 p-3 rounded-xl border cursor-pointer ${answers[q.id]===opt?"border-primary bg-primary/5":"border-gray-100 hover:border-gray-200"}`}><input type="radio" name={q.id} value={opt} checked={answers[q.id]===opt} onChange={()=>setAnswers({...answers,[q.id]:opt})} className="w-4 h-4 text-primary"/><span className="text-sm text-gray-700">{opt}</span></label>))}</div></div>)})}</div><button onClick={submit} disabled={submitting} className="w-full bg-amber-600 hover:bg-amber-700 text-white font-semibold py-3.5 rounded-xl disabled:opacity-50">{submitting?"Submitting...":"Submit Final Exam"}</button></div>);
}
