"use client";
import { useEffect, useState } from "react";
import { Search, Ban, CheckCircle, Trash2 } from "lucide-react";
export default function P() {
  const [users,setUsers]=useState<any[]>([]);const [srch,setSrch]=useState("");const [rol,setRol]=useState("");const [l,setL]=useState(true);
  const loadUsers=()=>{const p=new URLSearchParams();if(srch)p.set("search",srch);if(rol)p.set("role",rol);fetch("/api/admin/users?"+p).then(r=>r.json()).then(d=>{setUsers(d.users||[]);setL(false)});};
  useEffect(()=>{loadUsers()},[rol]);
  const ban=async(id:string,b:boolean)=>{await fetch("/api/admin/users/"+id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({isBanned:b,banReason:b?"Admin action":null})});loadUsers();};
  const del=async(id:string)=>{if(!confirm("Delete?"))return;await fetch("/api/admin/users/"+id,{method:"DELETE"});loadUsers();};
  if(l) return <div className="flex justify-center py-16"><div className="w-8 h-8 border-2 border-primary border-t-transparent rounded-full animate-spin"/></div>;
  return (<div className="space-y-6 animate-fade-in"><div><h1 className="text-2xl font-bold text-gray-900">User Management</h1><p className="text-gray-500 mt-1">Manage all platform users</p></div><div className="flex flex-wrap gap-3"><div className="relative flex-1 max-w-sm"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400"/><input placeholder="Search..." value={srch} onChange={e=>setSrch(e.target.value)} onKeyDown={e=>e.key==="Enter"&&loadUsers()} className="w-full pl-10 pr-4 py-2.5 rounded-xl border border-gray-200 text-sm"/></div><select value={rol} onChange={e=>setRol(e.target.value)} className="px-4 py-2.5 rounded-xl border border-gray-200 text-sm bg-white"><option value="">All</option><option value="ADMIN">Admin</option><option value="TEACHER">Teacher</option><option value="STUDENT">Student</option></select><button onClick={loadUsers} className="px-4 py-2.5 bg-primary text-white text-sm rounded-xl">Search</button></div><div className="card-premium overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-gray-50 border-b border-gray-100"><tr><th className="text-left px-6 py-3 font-medium text-gray-500">User</th><th className="text-left px-6 py-3 font-medium text-gray-500">Email</th><th className="text-left px-6 py-3 font-medium text-gray-500">Role</th><th className="text-left px-6 py-3 font-medium text-gray-500">Actions</th></tr></thead><tbody>{users.map(u=>(<tr key={u.id} className="border-b border-gray-50 hover:bg-gray-50/50"><td className="px-6 py-3"><div className="flex items-center gap-3"><div className="w-8 h-8 rounded-full bg-primary/10 flex items-center justify-center text-xs font-bold text-primary">{u.firstName[0]}{u.lastName[0]}</div><span className="font-medium">{u.firstName} {u.lastName}</span></div></td><td className="px-6 py-3 text-gray-500">{u.email}</td><td className="px-6 py-3"><span className={`text-xs font-medium px-2 py-0.5 rounded-full ${u.role==="ADMIN"?"bg-red-100 text-red-700":u.role==="TEACHER"?"bg-emerald-100 text-emerald-700":"bg-violet-100 text-violet-700"}`}>{u.role}</span></td><td className="px-6 py-3"><div className="flex gap-2"><button onClick={()=>ban(u.id,!u.isBanned)} className={`p-1.5 rounded-lg ${u.isBanned?"bg-green-50 text-green-600":"bg-red-50 text-red-600"}`}>{u.isBanned?<CheckCircle className="w-4 h-4"/>:<Ban className="w-4 h-4"/>}</button><button onClick={()=>del(u.id)} className="p-1.5 rounded-lg bg-gray-50 text-gray-400 hover:text-red-600"><Trash2 className="w-4 h-4"/></button></div></td></tr>))}</tbody></table></div></div></div>);
}
