"use client";
import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { ArrowLeft, CheckCircle, XCircle, Brain, Clock } from "lucide-react";
export default function P() {
  const params=useParams();const router=useRouter();const [quiz,setQuiz]=useState<any>(null);const [answers,setAnswers]=useState<Record<string,string>>({});const [submitted,setSubmitted]=useState(false);const [result,setResult]=useState<any>(null);const [details,setDetails]=useState<any[]>([]);const [l,setL]=useState(true);const [submitting,setSubmitting]=useState(false);
  useEffect(()=>{fetch("/api/quizzes/"+params.id).then(r=>r.json()).then(d=>{setQuiz(d.quiz);setL(false)});},[params.id]);
  const submit=async()=>{if(submitting)return;setSubmitting(true);const res=await fetch("/api/quizzes/"+params.id+"/submit",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({answers})});const data=await res.json();setResult(data.attempt);setDetails(data.results);setSubmitted(true);setSubmitting(false);};
  if(l) return <div className="flex justify-center py-16"><div className="w-8 h-8 border-2 border-primary border-t-transparent rounded-full animate-spin"/></div>;
  if(!quiz) return <div className="py-16 text-center text-gray-500">Quiz not found</div>;
  if(submitted&&result){const p=result.isPassed;return (<div className="max-w-2xl mx-auto space-y-6 animate-scale-in"><div className={`card-premium p-8 text-center ${p?"border-emerald-200":"border-red-200"}`}><div className={`w-16 h-16 rounded-full mx-auto mb-4 flex items-center justify-center ${p?"bg-emerald-100":"bg-red-100"}`}>{p?<CheckCircle className="w-8 h-8 text-emerald-600"/>:<XCircle className="w-8 h-8 text-red-600"/>}</div><h1 className="text-2xl font-bold mb-2">{p?"Congratulations!":"Keep Trying!"}</h1><p className="text-gray-500 mb-6">{p?"You passed!":"You didn't meet the passing score."}</p><div className="flex justify-center gap-8 mb-6"><div><div className="text-3xl font-bold">{result.score}/{result.totalPoints}</div><div className="text-xs text-gray-500">Score</div></div><div className="w-px h-12 bg-gray-200"/><div><div className={`text-3xl font-bold ${p?"text-emerald-600":"text-red-600"}`}>{result.percentage}%</div><div className="text-xs text-gray-500">Pct</div></div></div><button onClick={()=>router.push("/student/classes/"+quiz.module.classId)} className="bg-primary text-white px-6 py-2.5 rounded-xl text-sm font-medium">Back to Class</button></div><div className="card-premium p-6"><h2 className="text-lg font-semibold mb-4">Review</h2><div className="space-y-4">{details.map((d:any,i:number)=>(<div key={i} className={`p-4 rounded-xl border ${d.isCorrect?"border-emerald-100 bg-emerald-50/30":"border-red-100 bg-red-50/30"}`}><div className="flex items-start gap-3">{d.isCorrect?<CheckCircle className="w-5 h-5 text-emerald-500 flex-shrink-0 mt-0.5"/>:<XCircle className="w-5 h-5 text-red-500 flex-shrink-0 mt-0.5"/>}<div><p className="text-sm font-medium">{d.questionText}</p><p className="text-xs text-gray-500 mt-1">Your answer: <span className={d.isCorrect?"text-emerald-600 font-medium":"text-red-600 font-medium"}>{d.yourAnswer||"(unanswered)"}</span></p>{!d.isCorrect&&<p className="text-xs text-emerald-600 mt-0.5">Correct: {d.correctAnswer}</p>}</div></div></div>))}</div></div></div>);}
  return (<div className="max-w-2xl mx-auto space-y-6 animate-fade-in"><button onClick={()=>router.back()} className="flex items-center gap-2 text-sm text-gray-500 hover:text-gray-900"><ArrowLeft className="w-4 h-4"/>Back</button><div className="card-premium p-6"><h1 className="text-xl font-bold">{quiz.title}</h1><p className="text-sm text-gray-500 mt-1">{quiz.description}</p><div className="flex items-center gap-4 mt-3 text-xs text-gray-500"><span className="flex items-center gap-1"><Brain className="w-3.5 h-3.5"/>{quiz.questions.length} questions</span>{quiz.timeLimit&&<span className="flex items-center gap-1"><Clock className="w-3.5 h-3.5"/>{quiz.timeLimit}min</span>}<span>Pass: {quiz.passingScore}%</span></div></div><div className="space-y-4">{quiz.questions.map((q:any,i:number)=>{const opts:string[]=JSON.parse(q.options);return (<div key={q.id} className="card-premium p-5"><p className="text-sm font-semibold mb-3">{i+1}. {q.questionText}</p><div className="space-y-2">{opts.map((opt:string)=>(<label key={opt} className={`flex items-center gap-3 p-3 rounded-xl border cursor-pointer ${answers[q.id]===opt?"border-primary bg-primary/5":"border-gray-100 hover:border-gray-200"}`}><input type="radio" name={q.id} value={opt} checked={answers[q.id]===opt} onChange={()=>setAnswers({...answers,[q.id]:opt})} className="w-4 h-4 text-primary"/><span className="text-sm text-gray-700">{opt}</span></label>))}</div></div>)})}</div><button onClick={submit} disabled={submitting} className="w-full bg-primary hover:bg-primary-light text-white font-semibold py-3.5 rounded-xl transition-colors disabled:opacity-50">{submitting?"Submitting...":"Submit Quiz"}</button></div>);
}
