"use client";
import { useEffect, useState } from "react";
import { Trophy, Medal } from "lucide-react";
export default function P() {
  const [entries,setEntries]=useState<any[]>([]);const [l,setL]=useState(true);
  useEffect(()=>{fetch("/api/leaderboard").then(r=>r.json()).then(d=>{setEntries(d.leaderboard||[]);setL(false)});},[]);
  if(l) return <div className="flex justify-center py-16"><div className="w-8 h-8 border-2 border-primary border-t-transparent rounded-full animate-spin"/></div>;
  const top3=entries.filter(e=>e.rank&&e.rank<=3);
  return (<div className="space-y-8 animate-fade-in"><div><h1 className="text-2xl font-bold text-gray-900">Leaderboard</h1><p className="text-gray-500 mt-1">Top performers across your classes</p></div>
    {top3.length>0&&(<div className="grid md:grid-cols-3 gap-6">{top3.map(e=>(<div key={e.id} className={`card-premium p-6 text-center ${e.rank===1?"border-amber-200 bg-amber-50/30":e.rank===2?"border-gray-200 bg-gray-50/30":"border-orange-200 bg-orange-50/30"}`}><div className="flex justify-center mb-3">{e.rank===1?<Trophy className="w-10 h-10 text-amber-500"/>:e.rank===2?<Medal className="w-10 h-10 text-gray-400"/>:<Medal className="w-10 h-10 text-orange-400"/>}</div><div className="w-16 h-16 rounded-full bg-primary/10 flex items-center justify-center text-xl font-bold text-primary mx-auto mb-3">{e.student?.user.firstName?.[0]}{e.student?.user.lastName?.[0]}</div><h3 className="font-semibold">{e.student?.user.firstName} {e.student?.user.lastName}</h3><p className="text-xs text-gray-500 mt-1">{e.class?.name}</p><div className="mt-3 text-2xl font-bold text-primary">{e.totalScore.toFixed(0)}%</div><span className="text-xs font-medium">Rank #{e.rank}</span></div>))}</div>)}
    <div className="card-premium overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-gray-50 border-b border-gray-100"><tr><th className="text-left px-6 py-3 font-medium text-gray-500 w-16">Rank</th><th className="text-left px-6 py-3 font-medium text-gray-500">Student</th><th className="text-left px-6 py-3 font-medium text-gray-500">Class</th><th className="text-left px-6 py-3 font-medium text-gray-500">Score</th></tr></thead><tbody>{entries.map(e=>(<tr key={e.id} className="border-b border-gray-50 hover:bg-gray-50/50"><td className="px-6 py-3"><span className={`flex items-center justify-center w-8 h-8 rounded-full text-xs font-bold ${e.rank===1?"bg-amber-100 text-amber-700":e.rank===2?"bg-gray-100 text-gray-600":e.rank===3?"bg-orange-100 text-orange-700":"bg-gray-50 text-gray-500"}`}>{e.rank||"-"}</span></td><td className="px-6 py-3 font-medium">{e.student?.user.firstName} {e.student?.user.lastName}</td><td className="px-6 py-3 text-gray-500">{e.class?.name}</td><td className="px-6 py-3 font-semibold">{e.totalScore.toFixed(0)}%</td></tr>))}</tbody></table></div></div></div>);
}
