"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { BookOpen, Users, FileText, Activity } from "lucide-react";
export default function P() {
  const router=useRouter();const [cls,setCls]=useState<any[]>([]);const [l,setL]=useState(true);
  useEffect(()=>{fetch("/api/classes").then(r=>r.json()).then(d=>{setCls(d.classes||[]);setL(false)});},[]);
  const ts=cls.reduce((s,c)=>s+(c._count?.students||0),0);const tm=cls.reduce((s,c)=>s+(c._count?.modules||0),0);
  if(l) return <div className="flex justify-center py-16"><div className="w-8 h-8 border-2 border-primary border-t-transparent rounded-full animate-spin"/></div>;
  return (<div className="space-y-8 animate-fade-in"><div><h1 className="text-2xl font-bold text-gray-900">Teacher Dashboard</h1><p className="text-gray-500 mt-1">Manage your classes and students</p></div><div className="grid grid-cols-2 md:grid-cols-4 gap-4">{[{icon:BookOpen,label:"My Classes",value:cls.length,c:"bg-blue-50 text-blue-600"},{icon:Users,label:"Total Students",value:ts,c:"bg-violet-50 text-violet-600"},{icon:FileText,label:"Modules",value:tm,c:"bg-emerald-50 text-emerald-600"},{icon:Activity,label:"Active",value:cls.filter(c=>c.isPublished).length,c:"bg-amber-50 text-amber-600"}].map((x,i)=>(<div key={i} className="card-premium p-4"><div className={`w-10 h-10 rounded-xl ${x.c} flex items-center justify-center mb-3`}><x.icon className="w-5 h-5"/></div><div className="text-2xl font-bold">{x.value}</div><div className="text-xs text-gray-500 mt-0.5">{x.label}</div></div>))}</div><div className="card-premium p-6"><h2 className="text-lg font-semibold mb-4">My Classes</h2><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">{cls.map(c=>(<div key={c.id} onClick={()=>router.push("/teacher/classes/"+c.id)} className="p-4 rounded-xl border border-gray-100 hover:border-gray-200 hover:shadow-sm cursor-pointer"><div className="flex justify-between mb-2"><span className="text-xs font-medium text-primary bg-primary/5 px-2 py-0.5 rounded-full">{c.code}</span><span className={`text-xs px-2 py-0.5 rounded-full ${c.isPublished?"bg-green-50 text-green-700":"bg-gray-100 text-gray-500"}`}>{c.isPublished?"Live":"Draft"}</span></div><h3 className="font-semibold">{c.name}</h3><div className="flex items-center gap-3 text-xs text-gray-500 mt-3"><span className="flex items-center gap-1"><Users className="w-3 h-3"/>{c._count?.students||0}</span><span className="flex items-center gap-1"><FileText className="w-3 h-3"/>{c._count?.modules||0}</span></div></div>))}</div></div></div>);
}
