"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { BookOpen, Brain, Award, Target, ChevronRight } from "lucide-react";
export default function P() {
  const router=useRouter();const [cls,setCls]=useState<any[]>([]);const [certs,setCerts]=useState<any[]>([]);const [l,setL]=useState(true);
  useEffect(()=>{Promise.all([fetch("/api/classes").then(r=>r.json()),fetch("/api/certificates").then(r=>r.json())]).then(([cd,crd])=>{setCls(cd.classes||[]);setCerts(crd.certificates||[]);setL(false)});},[]);
  if(l) return <div className="flex justify-center py-16"><div className="w-8 h-8 border-2 border-primary border-t-transparent rounded-full animate-spin"/></div>;
  const tm=cls.reduce((s,c)=>s+(c._count?.modules||0),0);
  return (<div className="space-y-8 animate-fade-in"><div><h1 className="text-2xl font-bold text-gray-900">Student Dashboard</h1><p className="text-gray-500 mt-1">Your learning journey</p></div><div className="grid grid-cols-2 md:grid-cols-4 gap-4">{[{icon:BookOpen,label:"Classes",value:cls.length,c:"bg-blue-50 text-blue-600"},{icon:Brain,label:"Modules",value:tm,c:"bg-violet-50 text-violet-600"},{icon:Award,label:"Certificates",value:certs.length,c:"bg-amber-50 text-amber-600"},{icon:Target,label:"Active",value:cls.filter(c=>c.isPublished).length,c:"bg-emerald-50 text-emerald-600"}].map((x,i)=>(<div key={i} className="card-premium p-4"><div className={`w-10 h-10 rounded-xl ${x.c} flex items-center justify-center mb-3`}><x.icon className="w-5 h-5"/></div><div className="text-2xl font-bold">{x.value}</div><div className="text-xs text-gray-500 mt-0.5">{x.label}</div></div>))}</div><div className="card-premium p-6"><div className="flex justify-between mb-4"><h2 className="text-lg font-semibold">My Classes</h2><button onClick={()=>router.push("/student/classes")} className="text-sm text-primary font-medium">View All <ChevronRight className="w-4 h-4 inline"/></button></div>{cls.length===0?<p className="text-center text-gray-400 py-8">No classes enrolled.</p>:<div className="grid md:grid-cols-2 gap-4">{cls.map(c=>(<div key={c.id} onClick={()=>router.push("/student/classes/"+c.id)} className="p-4 rounded-xl border border-gray-100 hover:border-gray-200 hover:shadow-sm cursor-pointer"><span className="text-xs font-medium text-primary bg-primary/5 px-2 py-0.5 rounded-full">{c.code}</span><h3 className="font-semibold mt-2">{c.name}</h3><p className="text-xs text-gray-500 mt-1">{c._count?.modules||0} modules · {c.category}</p><div className="w-full bg-gray-100 rounded-full h-1.5 mt-3"><div className="h-1.5 rounded-full bg-primary" style={{width:"45%"}}/></div></div>))}</div>}</div>{certs.length>0&&(<div className="card-premium p-6"><h2 className="text-lg font-semibold mb-4">My Certificates</h2><div className="grid md:grid-cols-2 gap-4">{certs.map(c=>(<div key={c.id} className="flex items-center gap-4 p-4 rounded-xl border border-amber-100 bg-amber-50/30"><div className="w-10 h-10 rounded-lg bg-amber-100 flex items-center justify-center"><Award className="w-5 h-5 text-amber-600"/></div><div className="flex-1"><p className="font-medium text-sm">{c.class?.name}</p><p className="text-xs text-gray-500">Score: {c.score}/20 · {new Date(c.issueDate).toLocaleDateString()}</p></div><span className="text-xs font-medium text-green-600 bg-green-50 px-2 py-0.5 rounded-full">Earned</span></div>))}</div></div>)}</div>);
}
