"use client";
import { useEffect, useState } from "react";
import { Users, BookOpen, Award, Activity } from "lucide-react";
export default function P() {
  const [s,setS]=useState<any>({});const [l,setL]=useState(true);
  useEffect(()=>{fetch("/api/admin/stats").then(r=>r.json()).then(d=>{setS(d.stats||{});setL(false)});},[]);
  if(l) return <div className="flex justify-center py-16"><div className="w-8 h-8 border-2 border-primary border-t-transparent rounded-full animate-spin"/></div>;
  return (<div className="space-y-8 animate-fade-in"><div><h1 className="text-2xl font-bold text-gray-900">Analytics</h1><p className="text-gray-500 mt-1">Platform-wide insights</p></div><div className="grid grid-cols-2 md:grid-cols-4 gap-4">{[{icon:Users,label:"Total Users",value:s?.totalUsers,change:"+12%"},{icon:BookOpen,label:"Classes",value:s?.totalClasses,change:"+5%"},{icon:Activity,label:"Quizzes",value:s?.totalQuizzes,change:"+24%"},{icon:Award,label:"Certificates",value:s?.certificates,change:"+18%"}].map((x,i)=>(<div key={i} className="card-premium p-6"><div className="flex justify-between mb-4"><div className="w-10 h-10 rounded-xl bg-primary flex items-center justify-center"><x.icon className="w-5 h-5 text-white"/></div><span className="text-xs font-medium text-green-600 bg-green-50 px-2 py-0.5 rounded-full">{x.change}</span></div><div className="text-3xl font-bold">{x.value??"-"}</div><div className="text-sm text-gray-500 mt-1">{x.label}</div></div>))}</div><div className="grid lg:grid-cols-2 gap-6"><div className="card-premium p-6"><h2 className="text-lg font-semibold mb-6">User Distribution</h2>{[{label:"Students",value:s?.totalStudents||0,total:s?.totalUsers||1,c:"bg-violet-500"},{label:"Teachers",value:s?.totalTeachers||0,total:s?.totalUsers||1,c:"bg-emerald-500"},{label:"Admins",value:s?.totalAdmins||0,total:s?.totalUsers||1,c:"bg-red-500"}].map(d=>(<div key={d.label}><div className="flex justify-between text-sm mb-1"><span className="font-medium">{d.label}</span><span className="text-gray-500">{d.value}</span></div><div className="w-full bg-gray-100 rounded-full h-2"><div className={`h-2 rounded-full ${d.c}`} style={{width:(d.value/(d.total||1))*100+"%"}}/></div></div>))}</div><div className="card-premium p-6"><h2 className="text-lg font-semibold mb-6">Content Overview</h2><div className="space-y-4">{[{l:"Classes",v:s?.totalClasses},{l:"Modules",v:s?.totalModules},{l:"Quizzes",v:s?.totalQuizzes},{l:"Videos",v:s?.totalVideos},{l:"Files",v:s?.totalFiles}].map(d=>(<div key={d.l} className="flex justify-between"><span className="text-sm font-medium">{d.l}</span><span className="text-sm font-semibold">{d.v}</span></div>))}</div></div></div></div>);
}
