"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Users, FileText, Plus, Trash2, Eye } from "lucide-react";
export default function P() {
  const router=useRouter();const [cls,setCls]=useState<any[]>([]);const [l,setL]=useState(true);const [sf,setSf]=useState(false);const [f,setF]=useState({name:"",code:"",description:"",category:"",semester:"Fall 2024",academicYear:"2024-2025",maxStudents:40,isPublished:true});
  const load=()=>{fetch("/api/classes").then(r=>r.json()).then(d=>{setCls(d.classes||[]);setL(false)});};
  useEffect(()=>{load()},[]);
  const create=async(e:React.FormEvent)=>{e.preventDefault();await fetch("/api/classes",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(f)});setSf(false);setF({name:"",code:"",description:"",category:"",semester:"Fall 2024",academicYear:"2024-2025",maxStudents:40,isPublished:true});load();};
  const del=async(id:string)=>{if(!confirm("Delete?"))return;await fetch("/api/classes/"+id,{method:"DELETE"});load();};
  if(l) return <div className="flex justify-center py-16"><div className="w-8 h-8 border-2 border-primary border-t-transparent rounded-full animate-spin"/></div>;
  return (<div className="space-y-6 animate-fade-in"><div className="flex justify-between"><div><h1 className="text-2xl font-bold text-gray-900">Classes</h1><p className="text-gray-500 mt-1">Manage all classes</p></div><button onClick={()=>setSf(!sf)} className="flex items-center gap-2 bg-primary text-white text-sm px-4 py-2.5 rounded-xl"><Plus className="w-4 h-4"/>New Class</button></div>{sf&&(<div className="card-premium p-6"><h2 className="text-lg font-semibold mb-4">Create Class</h2><form onSubmit={create} className="grid sm:grid-cols-2 gap-4"><input placeholder="Name" value={f.name} onChange={e=>setF({...f,name:e.target.value})} required className="px-4 py-2.5 rounded-xl border text-sm"/><input placeholder="Code" value={f.code} onChange={e=>setF({...f,code:e.target.value})} required className="px-4 py-2.5 rounded-xl border text-sm"/><input placeholder="Description" value={f.description} onChange={e=>setF({...f,description:e.target.value})} className="px-4 py-2.5 rounded-xl border text-sm sm:col-span-2"/><input placeholder="Category" value={f.category} onChange={e=>setF({...f,category:e.target.value})} className="px-4 py-2.5 rounded-xl border text-sm"/><div className="sm:col-span-2 flex gap-3"><button type="submit" className="bg-primary text-white px-6 py-2.5 rounded-xl text-sm">Create</button><button type="button" onClick={()=>setSf(false)} className="px-6 py-2.5 rounded-xl border text-sm">Cancel</button></div></form></div>)}<div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">{cls.map(c=>(<div key={c.id} className="card-premium p-6"><div className="flex justify-between mb-4"><div><span className="text-xs font-medium text-primary bg-primary/5 px-2 py-0.5 rounded-full">{c.code}</span><h3 className="text-lg font-semibold mt-2">{c.name}</h3></div><span className={`text-xs px-2 py-0.5 rounded-full ${c.isPublished?"bg-green-50 text-green-700":"bg-gray-100 text-gray-500"}`}>{c.isPublished?"Published":"Draft"}</span></div><p className="text-sm text-gray-500 mb-4">{c.category} · {c.semester}</p><div className="flex items-center gap-4 text-xs text-gray-500 mb-2"><span className="flex items-center gap-1"><Users className="w-3.5 h-3.5"/>{c._count?.students||0}</span><span className="flex items-center gap-1"><FileText className="w-3.5 h-3.5"/>{c._count?.modules||0}</span></div><div className="flex items-center gap-2 pt-4 border-t border-gray-100"><button onClick={()=>router.push("/admin/classes/"+c.id)} className="flex items-center gap-1.5 text-xs font-medium text-primary"><Eye className="w-3.5 h-3.5"/>View</button><div className="flex-1"/><button onClick={()=>del(c.id)} className="p-1 rounded text-gray-400 hover:text-red-600"><Trash2 className="w-3.5 h-3.5"/></button></div></div>))}</div></div>);
}
